# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Econ-Teach Notebooks
author: Jonathan Conning
logo: logo.png


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  exclude_patterns: []  

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/jhconning/Econ-Teach  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"   
  colab_url: "https://colab.research.google.com"
  thebe: false

parse:
  myst_enable_extensions: 
    - amsmath
    - dollarmath
    #    - colon_fence
    #- deflist
    #- html_image
#    - linkify
    #- replacements
    #- smartquotes
    #- substitution


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

only_build_toc_files: true